baseURL: http://www.x2q.net
disablePathToLower: true
languageCode: en-us
theme: hugo-PaperMod
title: x2q - my notes online


assets:
  # disableHLJS: true # to disable highlight.js
  # disableFingerprinting: true
  favicon: https://www.x2q.net/favicon.ico
  favicon16x16: https://www.x2q.net/favicon-16x16.png
  favicon32x32: https://www.x2q.net/favicon-32x32.png
