baseURL: http://www.x2q.net
disablePathToLower: true
languageCode: en-us
theme: hugo-PaperMod
title: x2q - my notes online


assets:
  # disableHLJS: true # to disable highlight.js
  # disableFingerprinting: true
  favicon: favicon.ico
  favicon16x16: favicon-16x16.png
  favicon32x32: favicon-32x32.png
